import { test, expect } from '@playwright/test'
import { captureEvidence, fillOrder, mockApi, orderFixture, stubTiles } from './fixtures'

test('registro válido muestra éxito y los datos guardados', async ({ page }) => {
  const api = await mockApi(page)
  await page.goto('/?vista=pedidos')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await fillOrder(page)
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Pedido guardado correctamente.' })).toBeVisible()
  await expect(page.getByRole('article', { name: 'Detalle del pedido seleccionado' })).toContainText('Registro ficticio')
  expect(api.calls.create).toBe(1)
  expect(api.orders.get('NUEVO-FICTICIO')?.window_start).toBe('2026-10-02T10:00:00-05:00')
})

test('campos obligatorios y ventana inválida no envían y conservan el formulario', async ({ page }) => {
  const api = await mockApi(page)
  await page.goto('/?vista=pedidos')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  expect(api.calls.create).toBe(0)
  await expect(page.getByLabel('Destinatario *', { exact: true })).toBeFocused()
  await fillOrder(page, 'Conservar lo escrito')
  await page.getByLabel('Fin de ventana · Lima *').fill('2026-10-02T09:00')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('fin posterior al inicio')
  await expect(page.getByLabel('Destinatario *', { exact: true })).toHaveValue('Conservar lo escrito')
  await expect(page.getByLabel('Dirección de entrega *', { exact: true })).toHaveValue('Dirección ficticia 456')
  await expect(page.getByLabel('Fin de ventana · Lima *')).toHaveValue('2026-10-02T09:00')
  await expect(page.getByLabel('Indicaciones adicionales')).toHaveValue('Entrega ficticia para pruebas.')
  expect(api.calls.create).toBe(0)
})

test('edición precarga datos y guarda campos permitidos con versión', async ({ page }) => {
  const api = await mockApi(page)
  await page.goto('/?vista=pedidos')
  await page.getByRole('row', { name: /PEDIDO-FICTICIO/ }).click()
  await page.getByRole('button', { name: 'Editar pedido', exact: true }).click()
  await expect(page.getByLabel('Destinatario *', { exact: true })).toHaveValue(orderFixture().customer)
  await expect(page.getByLabel('Inicio de ventana · Lima *')).toHaveValue('2026-10-01T10:00')
  await expect(page.getByLabel('Peso del paquete (kg) *')).toHaveValue('4.5')
  await expect(page.getByLabel('Indicaciones adicionales')).toHaveValue(orderFixture().instructions)
  await page.getByLabel('Destinatario *', { exact: true }).fill('Edición ficticia')
  await page.getByLabel('Peso del paquete (kg) *').fill('3.25')
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Pedido guardado correctamente.' })).toBeVisible()
  expect(api.calls.update).toBe(1)
  expect(api.orders.get('PEDIDO-FICTICIO')).toMatchObject({ customer: 'Edición ficticia', weight_kg: 3.25, version: 2, status: 'PENDIENTE', assigned: false })
})

test('cancelación: Volver conserva el pedido y confirmar lo cancela', async ({ page }) => {
  const api = await mockApi(page)
  await page.goto('/?vista=pedidos')
  await page.getByRole('button', { name: 'Cancelar pedido', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Volver', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(api.calls.cancel).toBe(0)
  expect(api.orders.get('PEDIDO-FICTICIO')).toEqual(orderFixture())
  await page.getByRole('button', { name: 'Cancelar pedido', exact: true }).click()
  await dialog.getByRole('button', { name: 'Sí, cancelar pedido', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Pedido cancelado. Su historial se conserva.' })).toBeVisible()
  await expect(page.getByRole('article', { name: 'Detalle del pedido seleccionado' })).toContainText('Cancelado')
  expect(api.calls.cancel).toBe(1)
  expect(api.orders.get('PEDIDO-FICTICIO')).toMatchObject({ status: 'CANCELADO', version: 2, customer: orderFixture().customer })
})

test('solo lectura no ofrece registro, edición ni cancelación', async ({ page }) => {
  const api = await mockApi(page, { readOnly: true })
  await page.goto('/?vista=pedidos')
  await expect(page.getByRole('grid', { name: 'Pedidos por estado' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Registrar pedido|Cancelar pedido/ })).toHaveCount(0)
  await page.getByRole('row', { name: /PEDIDO-FICTICIO/ }).click()
  await expect(page.getByRole('article', { name: 'Detalle del pedido seleccionado' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Registrar pedido|Editar pedido|Cancelar pedido/ })).toHaveCount(0)
  expect(api.calls).toEqual({ create: 0, update: 0, cancel: 0 })
})

test('error de API visible sin sustitución por demostración', async ({ page }) => {
  await mockApi(page, { failRead: true })
  await page.goto('/?vista=pedidos')
  await expect(page.getByRole('alert')).toContainText('sesión verificada')
  await expect(page.getByRole('button', { name: 'Volver a cargar' })).toBeVisible()
  await expect(page.getByText('Modo demostración', { exact: false })).toHaveCount(0)
  await expect(page.getByRole('grid')).toHaveCount(0)
})

test('fallo al guardar conserva los campos y no muestra éxito', async ({ page }) => {
  const api = await mockApi(page, { failWrite: true })
  await page.goto('/?vista=pedidos')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await fillOrder(page, 'Conservar ante error')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('No se pudo completar')
  await expect(page.getByLabel('Destinatario *', { exact: true })).toHaveValue('Conservar ante error')
  await expect(page.getByText('Pedido guardado correctamente.', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Modo demostración', { exact: false })).toHaveCount(0)
  expect(api.calls.create).toBe(1)
  expect(api.orders.size).toBe(1)
})

test('demostración explícita permite registrar, editar y cancelar con datos ficticios', async ({ page }) => {
  await stubTiles(page)
  await page.goto('/tests/ui/demo.html')
  await expect(page.getByRole('status').filter({ hasText: 'Modo demostración' })).toContainText('no hay sesión ni almacenamiento durable')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await fillOrder(page, 'Destinatario ficticio de evidencia')
  await page.getByRole('button', { name: 'Registrar pedido', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Pedido guardado correctamente.' })).toBeVisible()
  await captureEvidence(page, 'registro.png')
  await page.getByRole('button', { name: 'Editar pedido', exact: true }).click()
  await expect(page.getByLabel('Destinatario *', { exact: true })).toHaveValue('Destinatario ficticio de evidencia')
  await page.getByLabel('Peso del paquete (kg) *').fill('3.75')
  await page.getByLabel('Indicaciones adicionales').fill('Indicaciones editadas, exclusivamente ficticias.')
  await page.getByRole('button', { name: 'Guardar cambios', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Detalle del pedido seleccionado' })).toContainText('3,75 kg')
  await captureEvidence(page, 'edicion.png')
  await page.getByRole('button', { name: 'Cancelar pedido', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Sí, cancelar pedido', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Detalle del pedido seleccionado' })).toContainText('Cancelado')
  await captureEvidence(page, 'cancelacion.png')
})
